apiVersion: v1
kind: Pod
metadata:
  name: pod-ghost
  labels:
    name: myapp
spec:
  containers:
  - name: pod-ghost
    image: ghost:4
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 2368
