apiVersion: v1
kind: Pod
metadata:
  name: jeu-2048
  labels:
    name: myapp
spec:
  containers:
  - name: jeu-2048
    image: bgulla/2048:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
